# .github/workflows/pr.yml
name: Xcode Build on PR

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, macstudio]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo /usr/bin/xcode-select -s /Applications/Xcode.app

      - name: Install CocoaPods deps
        run: |
          # ensure cocoapods is available; skip if already installed
          if ! command -v pod >/dev/null; then
            sudo gem install cocoapods
          fi

          cd Channer
          pod install

      - name: Run Xcode Build
        id: build
        continue-on-error: true
        run: |
          xcodebuild -workspace Channer.xcworkspace \
                     -scheme Channer \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 16' \
                     build -verbose > full.log 2>&1
          echo "exit_code=$?" >> $GITHUB_OUTPUT
          grep -iE 'error:|fatal error:|Undefined symbols|CompileSwiftSources' full.log > errors.log || true

      - name: Upload error log artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-errors
          path: Channer/errors.log
          if-no-files-found: warn
          retention-days: 7

      - name: Post error log to PR
        if: steps.build.outputs.exit_code != '0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd Channer
          if [ ! -s errors.log ]; then
            ERRORS="⚠️ Build failed, but no explicit errors were found."
          else
            ERRORS=$(sed 's/`/\\`/g' errors.log)
          fi
          {
            echo "🚨 **Xcode Build Failed** on \`${{ github.head_ref }}\`"
            echo ""
            echo "<details><summary>Error log</summary>"
            echo ""
            echo '```log'
            echo "$ERRORS"
            echo '```'
            echo "</details>"
          } > comment.txt
          gh pr comment ${{ github.event.pull_request.number }} --body "$(cat comment.txt)"

      - name: Fail the job if build failed
        if: steps.build.outputs.exit_code != '0'
        run: exit 1
